// Code generated by go-bindata.
// sources:
// data/css/bootstrap-responsive.css
// data/css/bootstrap-responsive.min.css
// data/css/bootstrap.css
// data/css/bootstrap.min.css
// data/html/home.html
// data/img/glyphicons-halflings-white.png
// data/img/glyphicons-halflings.png
// data/js/bootstrap.js
// data/js/bootstrap.min.js
// DO NOT EDIT!

package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// dataCssBootstrapResponsiveCss reads file data from disk. It returns an error on failure.
func dataCssBootstrapResponsiveCss() (*asset, error) {
	path := "/Users/jc/code/go/src/github.com/stealthycoin/brainfuck/data/css/bootstrap-responsive.css"
	name := "data/css/bootstrap-responsive.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataCssBootstrapResponsiveMinCss reads file data from disk. It returns an error on failure.
func dataCssBootstrapResponsiveMinCss() (*asset, error) {
	path := "/Users/jc/code/go/src/github.com/stealthycoin/brainfuck/data/css/bootstrap-responsive.min.css"
	name := "data/css/bootstrap-responsive.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataCssBootstrapCss reads file data from disk. It returns an error on failure.
func dataCssBootstrapCss() (*asset, error) {
	path := "/Users/jc/code/go/src/github.com/stealthycoin/brainfuck/data/css/bootstrap.css"
	name := "data/css/bootstrap.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataCssBootstrapMinCss reads file data from disk. It returns an error on failure.
func dataCssBootstrapMinCss() (*asset, error) {
	path := "/Users/jc/code/go/src/github.com/stealthycoin/brainfuck/data/css/bootstrap.min.css"
	name := "data/css/bootstrap.min.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataHtmlHomeHtml reads file data from disk. It returns an error on failure.
func dataHtmlHomeHtml() (*asset, error) {
	path := "/Users/jc/code/go/src/github.com/stealthycoin/brainfuck/data/html/home.html"
	name := "data/html/home.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataImgGlyphiconsHalflingsWhitePng reads file data from disk. It returns an error on failure.
func dataImgGlyphiconsHalflingsWhitePng() (*asset, error) {
	path := "/Users/jc/code/go/src/github.com/stealthycoin/brainfuck/data/img/glyphicons-halflings-white.png"
	name := "data/img/glyphicons-halflings-white.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataImgGlyphiconsHalflingsPng reads file data from disk. It returns an error on failure.
func dataImgGlyphiconsHalflingsPng() (*asset, error) {
	path := "/Users/jc/code/go/src/github.com/stealthycoin/brainfuck/data/img/glyphicons-halflings.png"
	name := "data/img/glyphicons-halflings.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataJsBootstrapJs reads file data from disk. It returns an error on failure.
func dataJsBootstrapJs() (*asset, error) {
	path := "/Users/jc/code/go/src/github.com/stealthycoin/brainfuck/data/js/bootstrap.js"
	name := "data/js/bootstrap.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// dataJsBootstrapMinJs reads file data from disk. It returns an error on failure.
func dataJsBootstrapMinJs() (*asset, error) {
	path := "/Users/jc/code/go/src/github.com/stealthycoin/brainfuck/data/js/bootstrap.min.js"
	name := "data/js/bootstrap.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"data/css/bootstrap-responsive.css": dataCssBootstrapResponsiveCss,
	"data/css/bootstrap-responsive.min.css": dataCssBootstrapResponsiveMinCss,
	"data/css/bootstrap.css": dataCssBootstrapCss,
	"data/css/bootstrap.min.css": dataCssBootstrapMinCss,
	"data/html/home.html": dataHtmlHomeHtml,
	"data/img/glyphicons-halflings-white.png": dataImgGlyphiconsHalflingsWhitePng,
	"data/img/glyphicons-halflings.png": dataImgGlyphiconsHalflingsPng,
	"data/js/bootstrap.js": dataJsBootstrapJs,
	"data/js/bootstrap.min.js": dataJsBootstrapMinJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"data": &bintree{nil, map[string]*bintree{
		"css": &bintree{nil, map[string]*bintree{
			"bootstrap-responsive.css": &bintree{dataCssBootstrapResponsiveCss, map[string]*bintree{}},
			"bootstrap-responsive.min.css": &bintree{dataCssBootstrapResponsiveMinCss, map[string]*bintree{}},
			"bootstrap.css": &bintree{dataCssBootstrapCss, map[string]*bintree{}},
			"bootstrap.min.css": &bintree{dataCssBootstrapMinCss, map[string]*bintree{}},
		}},
		"html": &bintree{nil, map[string]*bintree{
			"home.html": &bintree{dataHtmlHomeHtml, map[string]*bintree{}},
		}},
		"img": &bintree{nil, map[string]*bintree{
			"glyphicons-halflings-white.png": &bintree{dataImgGlyphiconsHalflingsWhitePng, map[string]*bintree{}},
			"glyphicons-halflings.png": &bintree{dataImgGlyphiconsHalflingsPng, map[string]*bintree{}},
		}},
		"js": &bintree{nil, map[string]*bintree{
			"bootstrap.js": &bintree{dataJsBootstrapJs, map[string]*bintree{}},
			"bootstrap.min.js": &bintree{dataJsBootstrapMinJs, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

